// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnlYv8Hd7bWVd6q1R3_FUF0AV2aYXc_EI',
    appId: '1:746994458144:web:6011095c92e25c3b33a645',
    messagingSenderId: '746994458144',
    projectId: 'magic-touch-a71be',
    authDomain: 'magic-touch-a71be.firebaseapp.com',
    storageBucket: 'magic-touch-a71be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz8wc1vMybpWn6gf4yOGCQgs7nifx1Jb4',
    appId: '1:746994458144:android:597c5ae207ab1f3033a645',
    messagingSenderId: '746994458144',
    projectId: 'magic-touch-a71be',
    storageBucket: 'magic-touch-a71be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVXsu4N_mjFcOKOvrEu_-gL2UwkS00AY',
    appId: '1:746994458144:ios:8663c85b36c1610e33a645',
    messagingSenderId: '746994458144',
    projectId: 'magic-touch-a71be',
    storageBucket: 'magic-touch-a71be.firebasestorage.app',
    iosBundleId: 'com.example.magicTouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXVXsu4N_mjFcOKOvrEu_-gL2UwkS00AY',
    appId: '1:746994458144:ios:8663c85b36c1610e33a645',
    messagingSenderId: '746994458144',
    projectId: 'magic-touch-a71be',
    storageBucket: 'magic-touch-a71be.firebasestorage.app',
    iosBundleId: 'com.example.magicTouch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnlYv8Hd7bWVd6q1R3_FUF0AV2aYXc_EI',
    appId: '1:746994458144:web:897962c1188781be33a645',
    messagingSenderId: '746994458144',
    projectId: 'magic-touch-a71be',
    authDomain: 'magic-touch-a71be.firebaseapp.com',
    storageBucket: 'magic-touch-a71be.firebasestorage.app',
  );

}